# -*- coding: utf-8 -*-
"""Classification-transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYZszhqhy1ywd74qPFqDXrUj2TsnTpag
"""

!pip install transformers

from transformers import pipeline

classifire1 = pipeline('sentiment-analysis')## model = distilbert/distilbert-base-uncased
classifire2 = pipeline('sentiment-analysis',model = 'cardiffnlp/twitter-roberta-base-sentiment')

ex = 'I am a programmer, what is your magic power?'

classifire1(ex) , classifire2(ex)

