# -*- coding: utf-8 -*-
"""summarization text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Or7OJ4SsFeN0u2PU7pI56UXhCEMGH_sw
"""

from transformers import pipeline

summarizer = pipeline('summarization', model='sshleifer/distilbart-cnn-12-6')

text = '''Life is a beautiful journey, full of unexpected twists and turns, and it's up to us to embrace its whimsical nature with a light-hearted spirit. Like a delicate dance, we navigate through the highs and lows, savoring each step along the way.

In this grand theater of life, we are the playwrights, directors, and actors of our own stories. We hold the power to choose our roles and shape our destinies. Sometimes, we stumble upon challenges that seem insurmountable, but it is in those moments that our resilient spirit shines brightest.

Life's humor lies in its ability to surprise us when we least expect it. It throws curveballs, testing our adaptability and resilience. We learn to laugh at our mistakes, finding solace in the fact that nobody has all the answers. Embracing imperfections with a gentle smile, we discover the beauty in our vulnerabilities.

Amidst the chaos and uncertainty, life whispers little reminders of its beauty. It's in the warm embrace of a loved one, the laughter shared with friends, and the simple joys that bring a twinkle to our eyes. It's the small moments'''

ex = summarizer(text,max_length=50,min_length=20,do_sample=False)

print(ex)

len('Life is a beautiful journey, full of unexpected twists and turns, and its up to us to embrace its whimsical nature with a light-hearted spirit . Lifes humor lies in its ability to surprise us when we least expect it')

len(text)

