# -*- coding: utf-8 -*-
"""Zero-shot-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P35rUiOxLcpGWtDLocc0TNFbx9kNIgjK
"""

from transformers import pipeline

classifire = pipeline(task='zero-shot-classification')

ex = classifire(
    "the fifa World cup, often simply called the World Cup, is an international association football",
    candidate_labels=['sport','politics','finance']
)

print(ex)

